name: Build LaTeX document
on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'feat:') }}
    container:
      image: ghcr.io/jim-fx/tex
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 50

      - name: Generate expose.pdf
        run: make pdf FILE=expose

      - name: Generate expose-diff.pdf
        run: make pdf FILE=expose && make diff FILE=expose

      - name: Generate ideas.pdf
        run: make pdf FILE=ideas

      - uses: actions/upload-artifact@v4
        with:
          path: |
            expose.pdf
            expose-diff.pdf
            ideas.pdf

  create_release:
    permissions: write-all
    if: ${{ contains(github.event.head_commit.message, 'release') }}
    runs-on: ubuntu-latest
    needs: build_latex
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name:  v${{ github.run_number }}
          release_name: v${{ github.run_number }}
          draft: false
          prerelease: false

      - uses: actions/download-artifact@v4

      - name: Upload expose-diff.pdf
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./expose-diff.pdf
          asset_name: exposed-diff.pdf
          asset_content_type: application/pdf

      - name: Upload Expose.pdf
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./expose.pdf
          asset_name: expose.pdf
          asset_content_type: application/pdf

      - name: Upload Ideas.pdf
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./ideas.pdf
          asset_name: ideas.pdf
          asset_content_type: application/pdf
